# Site settings
title: 리디주식회사 RIDI Corporation
email: start@ridi.com
description: "리디북스, 리디스토리 서비스 제공 기업. 회사 소개 및 채용정보를 제공합니다."
url: "https://www.ridicorp.com"
enforce_ssl: www.ridicorp.com
baseurl: ""
google_analytics:
  ua: "UA-10567409-3"

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

collections:
  career:
    output: true
  press:
    output: true
  slides:
    output: true

defaults:
  # Pages
  -
    scope:
      path: "index.html"
    values:
      root_class: "about page"
  -
    scope:
      path: "branding.html"
    values:
      root_class: "branding page"
  -
    scope:
      path: "career/index.html"
    values:
      root_class: "career page"
  -
    scope:
      path: "blog/index.html"
    values:
      root_class: "posts blog page"
  -
    scope:
      path: "blog/slides.html"
    values:
      root_class: "slides blog page"
  -
    scope:
      path: "press/index.html"
    values:
      root_class: "press page"
  -
    scope:
      path: "press/photos.html"
    values:
      root_class: "photos press page"
  -
    scope:
      path: "contact.html"
    values:
      root_class: "contact page"

  # Posts
  -
    scope:
      type: "posts"
    values:
      root_class: "blog post"

# Pagination for blog posts
plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/blog/page:num/"

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "config.ru", "Gemfile", "Gemfile.lock"]
