# Site settings
title: 리디주식회사 RIDI Corporation
email: start@ridi.com
description: "리디북스, 리디스토리 서비스 제공 기업. 회사 소개 및 채용정보를 제공합니다."
url: "https://www.ridicorp.com"
enforce_ssl: www.ridicorp.com
baseurl: ""
google_analytics:
  ua: "UA-10567409-3"

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

collections:
  career:
    output: true
  press:
    output: true
  slide:
    output: true

# pagination for blog posts
plugins:
  - jekyll-paginate
paginate: 8
paginate_path: "/blog/page:num/"

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "config.ru", "Gemfile", "Gemfile.lock"]
